apiVersion: config.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  clusterNetwork: 
  - cidr: 10.244.0.0/16
    hostPrefix: 24
  serviceNetwork: 
  - 10.96.0.0/16
---
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  clusterNetwork: 
  - cidr: 10.244.0.0/16
    hostPrefix: 24
  serviceNetwork: 
  - 10.96.0.0/16
